name: Node.js Workflow

on: [push]  # Trigger the workflow on push events

jobs:
  run-node:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - uses: actions/checkout@v3  # Checkout the repository
      - uses: actions/setup-node@v4  # Set up Node.js
        with:
          node-version: 16  # Specify the Node.js version
      - run: cd ..  # Change directory to the parent directory
      - run: echo "listen" | node start.js  # Write "listen" to console input
